# Jumpsuit
- type: startingGear
  id: HeadofSecurityJumpsuitBlack
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSBlack

- type: startingGear
  id: HeadofSecurityJumpskirtBlack
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSBlack
