- type: loadout
  id: JackSecBoots
  equipment: JackSecBoots

- type: startingGear
  id: JackSecBoots
  equipment:
    shoes: ClothingShoesBootsJackSecFilled

#Genesis
#OuterClothing
- type: loadout
  id: ArmorVestSec
  equipment: ArmorVestSec

- type: startingGear
  id: ArmorVestSec
  equipment:
    outerClothing: ClothingOuterVestArmorSec
