- type: loadout
  id: JackSecBoots
  equipment:
    shoes: ClothingShoesBootsJackSecFilled

# Genesis
# OuterClothing
- type: loadout
  id: ArmorVestSec
  equipment:
    outerClothing: ClothingOuterVestArmorSec
