contact_links:
  - name: Предложение
    url: https://discord.gg/NdGYJ7VGMJ
    about: Свои предложения можете оставлять в соответствующем канале Discord.
  - name: Сообщить об уязвимости
    url: https://discord.gg/NdGYJ7VGMJ
    about: Пожалуйста, сообщайте о серьезных эксплойтах и уязвимостях безопасности @debiloid_3000 в Discord.
