# Jumpsuit
- type: loadout
  id: HeadOfSecurityCentComJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentComMilitary

# Head
- type: loadout
  id: HeadHatBeretHoSCentCom
  equipment:
    head: ClothingHeadHatHeadOfSecurityCentComBeret
