- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  startingGear: PrisonerGear
  alwaysUseSpawner: true
  canBeAntag: false
  icon: JobIconPrisoner
  supervisors: job-supervisors-security
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 3600
  special:
    - !type:AddImplantSpecial
      implants: [ TrackingImplant ]

- type: startingGear
  id: PrisonerGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: PrisonerPDA
    ears: ClothingHeadsetGrey

- type: chameleonOutfit
  id: PrisonerChameleonOutfit
  job: Prisoner
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBlack
