# Pistols
- type: startingGear
  id: WeaponPistolMk58
  equipment:
    pocket1: WeaponPistolMk58

- type: startingGear
  id: WeaponPistolMk68
  equipment:
    pocket1: WeaponPistolMk68

- type: startingGear
  id: WeaponPistolM1911
  equipment:
    pocket1: WeaponPistolM1911

- type: startingGear
  id: WeaponRevolverMateba
  equipment:
    pocket1: WeaponRevolverMateba

# Pocket 2
- type: startingGear
  id: MagazinePistol
  equipment:
    pocket2: MagazinePistol

- type: startingGear
  id: MagazinePistolHighCapacity
  equipment:
    pocket2: MagazinePistolHighCapacity

- type: startingGear
  id: SpeedLoaderMagnum
  equipment:
    pocket2: SpeedLoaderMagnum

# OuterClothing
- type: startingGear
  id: ArmorVestArmorSec
  equipment:
    outerClothing: ClothingOuterVestArmorSec

# Uniform
- type: startingGear
  id: HECUUniform
  equipment:
    jumpsuit: ClothingUniformHECU

# Shoes
- type: startingGear
  id: SpetsnazBoots
  equipment:
    shoes: ClothingShoesBootsSpetsnazFilled

# Mask
- type: startingGear
  id: SecurityMask
  equipment:
    mask: ClothingMaskGasSecurity

# Gloves
- type: startingGear
  id: SecurityGloves
  effects:
  - !type:GroupLoadoutEffect
    proto: SeniorOfficer
  equipment:
    gloves: ClothingHandsTacticalSecurity
