- type: job
  id: CentComOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentComOfficial
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 468000  # 130 hours
  startingGear: CentComOfficialGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  setPreference: true
  alwaysUseSpawner: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CentComOfficialGear
  equipment:
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSunglassesModified
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
  storage:
    back:
    - PenCentcom
    - BoxFolderBlack

- type: chameleonOutfit
  id: CentComOfficialOutfit
  job: CentComOfficial
  hasMindShield: true
  equipment:
    neck: ClothingNeckScarfStripedCentcom
    mask: ClothingMaskGasCentcom
