- type: job
  id: CentralCommandMedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobCentralCommandMedicalDoctor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 14400 #4 hrs
  startingGear: CentComDoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Medical
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Cryogenics
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: CentComDoctorGear
  equipment:
    id: MedicalPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  #storage:
    #back:
    #- Stuff
